config/routes.rb
Rails.application.routes.draw do
  root to: 'recipes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :recipes, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :step
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :stage
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Sid - Your Sourdough Buddy</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="shortcut icon" href="https://www.mailbutler.io/images/favicons/favicon-16x16.png">
    <%= favicon_link_tag 'favicon.png' %>
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/recipes/index.html.erb
<h2>This is the recipes.index page</h2>

<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= asset_path('index_banner') %>);">
</div>

<% @recipes.each do |recipe| %>
  <%= link_to recipe.name, recipe_path(recipe) %>
<% end %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>